#!/usr/bin/env node

/**
 * Quick setup helper for IntelliPath local development
 * 
 * Usage: npm run setup
 * 
 * This script helps you configure .env files for local development
 */

const fs = require('fs');
const path = require('path');

const serverEnv = `# IntelliPath Server - Development Configuration
# Generated by setup script - customize as needed

NODE_ENV=development
PORT=5000

# MongoDB - Start a local MongoDB instance or use MongoDB Atlas
MONGODB_URI=mongodb://localhost:27017/intellipath_dev

# JWT Secrets - Generate with: node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
JWT_SECRET=your-dev-jwt-secret-here-change-me
JWT_REFRESH_SECRET=your-dev-refresh-secret-here-change-me

# Frontend & Backend URLs
FRONTEND_URL=http://localhost:5173
BACKEND_URL=http://localhost:5000

# Google OAuth - Get from https://console.cloud.google.com
GOOGLE_CLIENT_ID=your-google-client-id.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=your-google-client-secret

# AI/Gemini - Get from https://makersuite.google.com/app/apikey
GEMINI_API_KEY=your-gemini-api-key

# Email (Optional for local dev - comment out to skip)
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_USER=your-email@gmail.com
# SMTP_PASS=your-app-password

# Cloudinary (Optional)
# CLOUDINARY_CLOUD_NAME=your-cloud-name
# CLOUDINARY_API_KEY=your-api-key
# CLOUDINARY_API_SECRET=your-api-secret
`;

const clientEnv = `# IntelliPath Client - Development Configuration
# Generated by setup script - customize as needed

VITE_API_URL=http://localhost:5000

# Google OAuth Client ID - Must match server GOOGLE_CLIENT_ID
# Get from https://console.cloud.google.com
VITE_GOOGLE_CLIENT_ID=your-google-client-id.apps.googleusercontent.com
`;

const writeEnv = (filePath, content, name) => {
  if (fs.existsSync(filePath)) {
    console.log(`✓ ${name} already exists at ${filePath}`);
    return false;
  }
  fs.writeFileSync(filePath, content);
  console.log(`✓ Created ${name} at ${filePath}`);
  return true;
};

console.log('\n=== IntelliPath Development Setup ===\n');

const serverPath = path.join(__dirname, '..', '.env');
const clientPath = path.join(__dirname, '..', '..', 'client', '.env');

const serverCreated = writeEnv(serverPath, serverEnv, 'Server .env');
const clientCreated = writeEnv(clientPath, clientEnv, 'Client .env');

console.log('\n=== Next Steps ===\n');

if (serverCreated || clientCreated) {
  console.log('1. Edit the .env files with your actual configuration:');
  if (serverCreated) console.log(`   - ${serverPath}`);
  if (clientCreated) console.log(`   - ${clientPath}`);
  console.log('\n2. Start MongoDB (if not using Atlas):');
  console.log('   mongod');
  console.log('\n3. Start the backend:');
  console.log('   npm run dev');
  console.log('\n4. In another terminal, start the frontend:');
  console.log('   cd ../client && npm run dev');
  console.log('\n5. Test the setup:');
  console.log('   npm run smoke-tests');
} else {
  console.log('✓ .env files already exist. No changes made.');
  console.log('\nTo verify setup, run:');
  console.log('   npm run validate-env');
  console.log('   npm run smoke-tests');
}

console.log('\n=== Common Issues ===\n');
console.log('ERR_CONNECTION_REFUSED: Backend not running');
console.log('  → Run: npm run dev\n');
console.log('Login 500 error: Password validation failed');
console.log('  → Backend now validates password field\n');
console.log('Forgot password SSL error: SMTP not configured');
console.log('  → Set SMTP_* env vars or leave commented for dev\n');
console.log('Google sign-in 403: Client ID mismatch');
console.log('  → Ensure VITE_GOOGLE_CLIENT_ID matches GOOGLE_CLIENT_ID\n');

process.exit(0);
